#!/bin/bash

read -p "Enter 2 numbers to Sum: " num1 num2

sum=$((num1+num2))

echo "$num1 + $num2 = $sum"

read -sp "Enter the code: " secret

if [ "$secret" == "password" ]; then
   echo "Enter"
else
   echo "Wrong Password"
fi

